<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.1.0</Version>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <BuildOnPack>true</BuildOnPack>
    <PackageId>arcIsaProcessMermaid.Core</PackageId>
    <Description>Reusable library for ArcIsaProcessMermaid functions</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Include="ArcSiren.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ARCtrl" Version="3.0.3" />
    <PackageReference Include="ARCtrl.QueryModel" Version="3.0.0-alpha.1" />
    <PackageReference Include="Argu" Version="6.2.4" />
    <PackageReference Include="Siren" Version="0.3.2" />
    <None Include="README.md" Pack="true" PackagePath=""/>
    <None Include="../../LICENSE" Pack="true" PackagePath=""/>
  </ItemGroup>

</Project>