<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.1.0-alpha.1</Version>
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>arcIsaProcessMermaid</ToolCommandName>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <BuildOnPack>true</BuildOnPack>
    <PackageId>arcIsaProcessMermaid</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>CLI tool for ArcIsaProcessMermaid</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ArcUtils.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../arcIsaProcessMermaid.Core/arcIsaProcessMermaid.Core.fsproj" />
    <PackageReference Include="ARCtrl" Version="3.0.3" />
    <PackageReference Include="Argu" Version="6.2.4" />
    <PackageReference Include="Siren" Version="0.3.2" />
    <None Include="../../README.md" Pack="true" PackagePath=""/>
    <None Include="../../LICENSE" Pack="true" PackagePath=""/>
  </ItemGroup>

</Project>