<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.0.2</VersionPrefix>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>arcIsaProcessMermaid</ToolCommandName>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ArcProcesses.fs" />
    <Compile Include="MermaidStyling.fs" />
    <Compile Include="ArcUtils.fs" />
    <Compile Include="ArcSiren.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ARCtrl.NET" Version="2.0.2" />
    <PackageReference Include="ARCtrl.QueryModel" Version="2.0.2" />
    <PackageReference Include="Argu" Version="6.2.4" />
    <PackageReference Include="Siren" Version="0.3.2" />
    <None Include="../../README.md" Pack="true" PackagePath=""/>
    <None Include="../../LICENSE" Pack="true" PackagePath=""/>
  </ItemGroup>

</Project>